name: Build And Soundness checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        working-directory: backend
        run: swift build

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_enabled: true
      license_header_check_project_name: "Swift Foundation Models Playground"
      shell_check_enabled: false
      python_lint_check_enabled: false
      api_breakage_check_enabled: false
      # api_breakage_check_container_image: "swift:6.0-noble"
      docs_check_container_image: "swift:6.0-noble"
      format_check_container_image: "swift:6.0-noble"
      yamllint_check_enabled: true
